module.exports = {
  env: {
    es6: true,
    browser: true,
  },
  extends: ['airbnb', 'plugin:prettier/recommended', 'prettier/react', 'plugin:react/recommended'],
  plugins: [
    'prettier',
    'flowtype',
    'import',
    'babel',
    'react-hooks',
  ],
  parser: 'babel-eslint',
  parserOptions: {
    ecmaVersion: 11,
    ecmaFeatures: {
      experimentalObjectRestSpread: true,
    },
  },
  settings: {
    flowtype: {
      onlyFilesWithFlowAnnotation: true,
    },
    'import/resolver': {
      webpack: {
        config: 'webpack.config.base',
      },
    },
  },
  globals: {
  },
  rules: {
    'no-underscore-dangle': [0],
    'prefer-destructuring': ['error', { object: true, array: false }],
    'arrow-body-style': ['error', 'as-needed'],
    'prefer-arrow-callback': 'error',
    'no-confusing-arrow': [0],
    'function-paren-newline': 0,
    'max-len': 0,
    'linebreak-style': [0],
    'arrow-parens': ['error', 'as-needed'],
    'no-mixed-operators': [0],
    'no-floating-decimal': 0,
    'no-multiple-empty-lines': 0,
    'no-use-before-define': 0,
    'func-names': 0,
    camelcase: 0,
    eqeqeq: 1,
    'react/display-name': ['off'],
    'react/static-property-placement': [0],
    'react/sort-comp': [0],
    'react/jsx-props-no-spreading': ['off', { html: 'ignore', custom: 'ignore' }],
    'react/destructuring-assignment': ['off', 'always', { ignoreClassFields: true }],
    'react/no-unescaped-entities': [0],
    'react/jsx-closing-bracket-location': [0],
    'react/jsx-fragments': ['off', 'element'],
    'react/jsx-filename-extension': [1, { extensions: ['.js', '.jsx'] }],
    'react/prefer-es6-class': [2, 'always'],
    'react/default-props-match-prop-types': [0],
    'react/jsx-no-bind': [0],
    'react/forbid-prop-types': [1, { forbid: ['any'] }],
    'react/no-array-index-key': [0],
    'react/jsx-indent': 0,
    'react/no-unused-prop-types': [2, { skipShapeProps: true }],
    'react/prop-types': [0],
    'react-hooks/rules-of-hooks': 'error',
    'react-hooks/exhaustive-deps': 'warn',
    'import/extensions': [0],
    'import/no-named-as-default': 0,
    'import/prefer-default-export': 0,
    'import/no-extraneous-dependencies': ['error', { devDependencies: false, optionalDependencies: false, peerDependencies: false }],
    'import/no-cycle': [2, { maxDepth: 1 }],
    'flowtype/require-parameter-type': 0,
    'flowtype/require-return-type': [0, 'never', {
      excludeMatching: ['componentWillMount', 'componentWillUnmount'],
    }],
    'jsx-a11y/label-has-associated-control': [0],
    'jsx-a11y/label-has-for': [0],
    'jsx-a11y/anchor-is-valid': [0],
  },
};
